name: organoid-seg
channels:
  - conda-forge
dependencies:
  - python
  - openjdk=11
  - pyimagej
  - scikit-image
  - matplotlib
  - pandas
  - pyyaml
  - tqdm
  - pip
  - pip:
    - binarymeshformat
    - questionary
    - numpy-stl
